<?php

namespace Acme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    /**
     * @param bool|false $limit
     * @param null $city
     * @return array
     */
    public function getLastComments($limit = false, $city = null)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('c')
            ->from('AcmeMainBundle:Comment', 'c');

        $query
            ->orderBy('c.id', 'DESC');

        if ($city) {
            $query
                ->join('c.company', 'company')
                ->join('company.city', 'city');
            $query
                ->where('city.id = :cityId')
                ->setParameter('cityId', $city->getId());
        }

        if ($limit) {
            $query->setMaxResults($limit);
        }

        $result = $query->getQuery()->getResult();

        return $result;
    }

    /**
     * @param string $cityUrl
     * @return array
     */
    public function getCommentsByCity($cityUrl)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('c, com, city')
            ->from('AcmeMainBundle:Comment', 'c');
        $query->join('c.company', 'com');
        $query->join('com.city', 'city');
        $query->where('city.url = :url');

        $query
            ->orderBy('c.id', 'DESC');
        $query->setParameter('url', $cityUrl);


        $result = $query->getQuery()->getResult();

        return $result;
    }
}
