<?php

namespace Acme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{

    /**
     * @param bool $id
     * @param bool $limit
     * @return array
     */
    public function getTop($id = false, $limit = false)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('c')
            ->from('AcmeMainBundle:Company', 'c');

        if ($id)
            $query
                ->where('c.id != :cId')
                ->setParameter('cId', $id);

        $query
            ->orderBy('c.rating', 'DESC')
            ->addOrderBy('c.id');

        return $query->getQuery()->getResult();
    }

}
