<?php

namespace Acme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{

	/**
	 * @param bool|integer $id
	 * @param bool|integer $limit
	 * @param null|City $city
	 * @return array
	 */
    public function getTop($id = false, $limit = false, $city = null)
    {
		$query = $this->createQueryBuilder('c')
			->where('c.status = :status')
			->setParameter('status', Company::STATUS_ON)

			->orderBy('c.rating', 'DESC')
			->addOrderBy('c.id', 'DESC')
		;

        if ($id) {
			$query
				->where('c.id != :cId')
				->setParameter('cId', $id)
			;
		}


        if ($city) {
            $query
				->join('c.city', 'city')
                ->where('city.id = :cityId')
                ->setParameter('cityId', $city->getId())
			;
        }

        if ($limit)
            $query->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }

	/**
	 * @param City $city
	 * @param int $limit
	 * @return array
	 */
	public function getPopularByCity(City $city, $limit = 4)
	{
		$query = $this->createQueryBuilder('com')
			->join('com.city', 'city')

			->where('city.id = :cityId AND com.status = :status')
			->setParameter('cityId', $city->getId())
//			->andWhere('com.status = :status')
			->setParameter('status', Company::STATUS_ON)

			->orderBy('com.rating', 'DESC')

			->setMaxResults($limit)
			;

		return $query->getQuery()->getResult();
    }
}
